### PR TITLE
Api design fix

### LINKED ISSUE #77: Fix the API Design
Fix up the current API design to match the page created in the docs

### PR DESCRIPTION
**Pull request by Heckin-Doggo**
Behold, RESTful API.
image

All endpoints have been updated to the following:
- getBranches no longer needs to be POSTed.
- verbs no longer appear in endpoint names. They now follow CRUD (Create, Read, Update, Delete) model using POST, GET, PUT, DELETE.
- changed base nouns to being plural (i.e. user -> users, repository -> repositories)
- Some stuff that didn't use query parameters now uses query parameters.

This still needs to be updated in the wiki, but some stuff has already been updated over there. Swagger should be more up to date anyways.

Fixes #77

### CODE REVIEW

File: Tech@HubAPI/Tech@HubAPI/Controllers/UserController.cs [hunk 1]
```diff
@@ -160,23 +157,21 @@ public ActionResult<User> SignUp([FromBody] SignUpForm form)
             return user;
         }
 
-        [HttpPost]
+        [HttpPut]
```
Comment (mkmcary) [inline Tech@HubAPI/Tech@HubAPI/Controllers/UserController.cs:160]:
```suggestion
        [HttpPost]
        [Route("password")]
```

File: Tech@HubAPI/Tech@HubAPI/Controllers/UserController.cs [hunk 2]
```diff
@@ -160,23 +157,21 @@ public ActionResult<User> SignUp([FromBody] SignUpForm form)
...
         [Authorize]
         [Route("change")]
```
Comment (mkmcary) [inline Tech@HubAPI/Tech@HubAPI/Controllers/UserController.cs:162]:
```suggestion
```

**Review by mkmcary — DISMISSED** [review]

**Comment by Heckin-Doggo** [comment]
image

new endpoints

**Review by jpbream — APPROVED** [review]
